### ISSUE TITLE
implement package selector

### ISSUE THREAD

**Issue by christophsturm** [christophsturm/failfast#13]
```
Caused by: failfast.FailFastException: unknown selector in discovery request: selectors:PackageSelector [packageName = 'restaurant']
filters:IncludeClassNameFilter that includes class names that match one of the following regular expressions: 'restaurant\..*', ExcludeClassNameFilter that excludes class names that match one of the following regular expressions: 'com\.intellij\.rt.*' OR 'com\.intellij\.junit3.*'
	at failfast.junit.FailFastJunitTestEngine.findContexts(FailFastJunitTestEngine.kt:264)
	at failfast.junit.FailFastJunitTestEngine.discover(FailFastJunitTestEngine.kt:68)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:103)
	... 7 more
```

**Comment by christophsturm** [comment]
this would be pretty easy with classgraph which we probably should use. but currently we have no dependencies which is also pretty great.
